import type { ExamplePage } from './index';

export const jsonExamples: ExamplePage[] = [
	{
		slug: 'package-json',
		title: 'package.json config',
		description: 'A standard Node.js package manifest file setting up scripts and dependencies.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "name": "fmtly",\n  "version": "1.0.0",\n  "description": "Developer tools",\n  "main": "index.js",\n  "scripts": {\n    "build": "vite build",\n    "dev": "vite dev"\n  },\n  "dependencies": {\n    "svelte": "^5.0.0"\n  }\n}`,
		explanation:
			'The package.json file is the core configuration for Node.js projects. It defines dependencies, scripts, and metadata.',
		useCases: [
			'Setting up npm scripts',
			'Managing project dependencies',
			'Defining module entry points'
		],
		relatedTools: []
	},
	{
		slug: 'tsconfig-json',
		title: 'tsconfig.json config',
		description: 'TypeScript compiler configuration file example.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "strict": true,\n    "skipLibCheck": true\n  },\n  "include": ["src/**/*"]\n}`,
		explanation:
			'The tsconfig.json file configures how TypeScript compiles to JavaScript. It enables strict typing and module resolution.',
		useCases: [
			'Configuring TypeScript strictness',
			'Setting output targets',
			'Defining source folders'
		],
		relatedTools: []
	},
	{
		slug: 'eslintrc-json',
		title: '.eslintrc.json config',
		description: 'ESLint configuration for code quality rules.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "env": {\n    "browser": true,\n    "es2021": true\n  },\n  "extends": "eslint:recommended",\n  "parserOptions": {\n    "ecmaVersion": 12\n  },\n  "rules": {\n    "semi": ["error", "always"]\n  }\n}`,
		explanation:
			'ESLint uses this file to determine which linting rules to apply to JavaScript and TypeScript source files.',
		useCases: [
			'Enforcing coding standards',
			'Setting up environment globals',
			'Extending recommended rules'
		],
		relatedTools: []
	},
	{
		slug: 'prettierrc-json',
		title: '.prettierrc config',
		description: 'Prettier code formatting configuration.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "semi": true,\n  "trailingComma": "all",\n  "singleQuote": true,\n  "printWidth": 100,\n  "tabWidth": 2\n}`,
		explanation:
			'Prettier configurations control the automated formatting of your code, such as quote style and indentation.',
		useCases: ['Unifying code style', 'Configuring quote preferences', 'Setting line width limits'],
		relatedTools: []
	},
	{
		slug: 'vite-config-json',
		title: 'Vite config as JSON',
		description: 'A JSON representation of Vite build tools config.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "server": {\n    "port": 3000,\n    "strictPort": true\n  },\n  "build": {\n    "outDir": "dist",\n    "sourcemap": true\n  }\n}`,
		explanation:
			'While normally JavaScript, Vite configurations can be represented as JSON. It controls dev servers and build outputs.',
		useCases: ['Configuring dev server ports', 'Setting up build maps', 'Defining asset paths'],
		relatedTools: []
	},
	{
		slug: 'github-actions-json',
		title: 'GitHub Actions output',
		description: 'Context payload generated by GitHub Actions workflows.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "action": "opened",\n  "issue": {\n    "number": 42,\n    "title": "Bug in API",\n    "state": "open"\n  },\n  "repository": {\n    "name": "fmtly",\n    "full_name": "oguz/fmtly"\n  }\n}`,
		explanation:
			'GitHub Actions provide rich JSON contexts describing the event that triggered the workflow run.',
		useCases: [
			'Debugging workflow triggers',
			'Extracting PR numbers',
			'Checking repository details'
		],
		relatedTools: []
	},
	{
		slug: 'openapi-petstore-json',
		title: 'OpenAPI Petstore',
		description: 'A minimal OpenAPI 3.0 specification for a Petstore API.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "openapi": "3.0.0",\n  "info": {\n    "title": "Petstore API",\n    "version": "1.0"\n  },\n  "paths": {\n    "/pets": {\n      "get": {\n        "summary": "List all pets",\n        "responses": {\n          "200": {\n            "description": "A list of pets"\n          }\n        }\n      }\n    }\n  }\n}`,
		explanation:
			'OpenAPI files strictly define the structure of REST APIs. JSON is one of the two standard formats for OpenAPI.',
		useCases: ['Documenting API endpoints', 'Generating client SDKs', 'Validating API requests'],
		relatedTools: []
	},
	{
		slug: 'stripe-webhook-json',
		title: 'Stripe Webhook',
		description: 'A mock Stripe charge.succeeded webhook payload.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "id": "evt_123",\n  "type": "charge.succeeded",\n  "data": {\n    "object": {\n      "id": "ch_123",\n      "amount": 2000,\n      "currency": "usd",\n      "paid": true\n    }\n  }\n}`,
		explanation:
			'Stripe uses JSON webhooks to asynchronously notify your application of events like successful payments.',
		useCases: [
			'Simulating payment successes',
			'Testing webhook handlers',
			'Extracting transaction IDs'
		],
		relatedTools: []
	},
	{
		slug: 'github-pr-event-json',
		title: 'GitHub PR Event',
		description: 'A mock GitHub Pull Request webhook payload.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "action": "synchronize",\n  "number": 10,\n  "pull_request": {\n    "state": "open",\n    "head": {\n      "ref": "feature-branch"\n    }\n  }\n}`,
		explanation:
			'GitHub sends JSON payloads whenever events like Pull Requests changing occur in a repository.',
		useCases: ['Triggering CI pipelines', 'Processing PR approvals', 'Running integration tests'],
		relatedTools: []
	},
	{
		slug: 'json-ld-article-json',
		title: 'JSON-LD Article',
		description: 'Structured data for an Article, used for SEO.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "@context": "https://schema.org",\n  "@type": "Article",\n  "headline": "Understanding JSON",\n  "author": {\n    "@type": "Person",\n    "name": "Jane Doe"\n  },\n  "datePublished": "2024-01-01"\n}`,
		explanation:
			'JSON-LD is the modern standard for injecting Schema.org structured data into HTML pages for search engines.',
		useCases: ['Adding SEO snippets', 'Describing articles and authors', 'Generating Rich Results'],
		relatedTools: []
	},
	{
		slug: 'geojson-example',
		title: 'GeoJSON specificaton',
		description: 'A standard GeoJSON feature collection with a point and a polygon.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "type": "FeatureCollection",\n  "features": [\n    {\n      "type": "Feature",\n      "geometry": { "type": "Point", "coordinates": [102.0, 0.5] },\n      "properties": { "prop0": "value0" }\n    }\n  ]\n}`,
		explanation:
			'GeoJSON is a format for encoding a variety of geographic data structures like points, lines, and polygons.',
		useCases: [
			'Rendering maps with Leaflet',
			'Storing coordinates in databases',
			'Drawing polygon boundaries'
		],
		relatedTools: []
	},
	{
		slug: 'jwt-decoded-json',
		title: 'Decoded JWT header & payload',
		description: 'The JSON structure inside a standard authentication JWT.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "header": {\n    "alg": "HS256",\n    "typ": "JWT"\n  },\n  "payload": {\n    "sub": "1234567890",\n    "name": "John Doe",\n    "iat": 1516239022\n  }\n}`,
		explanation:
			'JSON Web Tokens consist of three parts. The header and payload are simply Base64URL-encoded JSON strings.',
		useCases: ['Decoding API tokens', 'Verifying user identity', 'Checking token expiration'],
		relatedTools: []
	},
	{
		slug: 'graphql-introspection-json',
		title: 'GraphQL Introspection',
		description: 'A mock output from a GraphQL introspection query.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "data": {\n    "__schema": {\n      "types": [\n        {\n          "name": "Query",\n          "kind": "OBJECT"\n        }\n      ]\n    }\n  }\n}`,
		explanation:
			'GraphQL introspection allows clients to query the server for its schema, returning a massive JSON tree.',
		useCases: [
			'Generating GraphQL clients',
			'Powering GraphiQL autocomplete',
			'Validating queries'
		],
		relatedTools: []
	},
	{
		slug: 'docker-inspect-json',
		title: 'docker inspect output',
		description: 'A mock JSON output from running docker inspect.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `[\n  {\n    "Id": "abc123xyz",\n    "State": {\n      "Status": "running",\n      "Running": true\n    },\n    "NetworkSettings": {\n      "IPAddress": "172.17.0.2"\n    }\n  }\n]`,
		explanation:
			'The docker inspect command outputs deep JSON structures containing everything about a container or image.',
		useCases: [
			'Extracting container IP addresses',
			'Checking container health',
			'Automating deployments'
		],
		relatedTools: []
	},
	{
		slug: 'package-lock-snippet',
		title: 'package-lock snippet',
		description: 'A fragment of an npm package-lock file.',
		toolUrl: '/json/formatter',
		toolName: 'JSON Formatter',
		format: 'json',
		content: `{\n  "name": "fmtly",\n  "lockfileVersion": 3,\n  "packages": {\n    "": {\n      "name": "fmtly",\n      "dependencies": { "svelte": "^5.0.0" }\n    }\n  }\n}`,
		explanation:
			'Lockfiles guarantee deterministic builds by pinning exact versions of all deeply nested dependencies.',
		useCases: [
			'Resolving dependency conflicts',
			'Auditing package versions',
			'Reproducible builds'
		],
		relatedTools: []
	}
];
