# fmtly — Windsurf Rules

Read this file entirely before writing any code.

---

## Stack

- SvelteKit 2 + TypeScript 5 + Tailwind CSS 4
- Cloudflare Pages (static) + Cloudflare Workers (network proxy only)
- Package manager: pnpm — never npm, never yarn
- Adapter: `@sveltejs/adapter-cloudflare`

---

## The Golden Rule

**Every tool runs in the browser. No user data ever touches a server.**

Exception: network tools (IP lookup, DNS lookup, HTTP headers, SSL checker) proxy through a minimal Cloudflare Worker. That Worker makes the network call and returns the result — it never logs or stores user data.

---

## Architecture Rules

### Tool Registry

Every tool is a config object in `src/lib/registry/tools/[category].tools.ts`.
Never create a route file for a tool — register it, the page generates itself.

### Lazy Loading — No Exceptions

Every processing library uses dynamic `import()`. Never at top level.

This applies to: `json-source-map`, `jsonrepair`, `ajv`, `js-yaml`, `fast-xml-parser`,
`papaparse`, `smol-toml`, `marked`, `diff`, `prettier`, `sql-formatter`, `svgo`,
`pdfjs-dist`, `pdf-lib`, `jszip`, `sheetjs`, `qrcode`, `jsqr`, `bwip-js`, `mathjs`,
`@faker-js/faker`, `quicktype-core`, `uuid`, `ulid`, `cron-parser`, `ua-parser-js`,
`browser-image-compression`, `exifr`, Monaco Editor.

**If it processes data → dynamic import.**

### No Backend for User Data

Permitted server-side code only:
- `+page.ts` load functions (read registry)
- `/sitemap.xml/+server.ts` (build time only)
- `workers/proxy/` (outbound network requests, no user data)

### Static Output Only

No Node.js APIs in browser code (`fs`, `path`, `crypto` module — use Web Crypto API).
No env vars in browser except `PUBLIC_` prefix.
Never delete `static/_headers`, `static/_redirects`, `static/_routes.json`.

---

## Code Rules

### TypeScript

- Strict mode. No `any`. No `@ts-ignore`. No `as unknown as X`.
- Every function: explicit param types and return type.

### Svelte Components

- PascalCase filenames.
- Props typed explicitly: `export let value: string`.
- No business logic in inline event handlers — extract to named functions.
- CSS: Tailwind first. `<style>` only for complex animations or pseudo-elements.

### Engines

- Location: `src/lib/engines/[category]/[name].engine.ts`
- Pure functions — no side effects, no store access, no DOM access.
- Input > 500KB → Web Worker.

### Stores & localStorage

- Shared state: `src/lib/stores/`
- localStorage: only in store files, never in components.

### CSS

- No hardcoded hex colors — always `var(--token-name)`.
- Tailwind arbitrary values: `bg-[var(--bg-surface)]`.
- Dark mode: `[data-theme="dark"]` on `<html>` — NOT Tailwind's `dark:` variant.

---

## Content Security Policy

`static/_headers` CSP must include:
- `style-src`: add `https://fonts.googleapis.com`
- `font-src`: add `https://fonts.gstatic.com`
- `script-src`: add `'unsafe-inline'` (required for SvelteKit inline scripts)
- `script-src`: add `https://static.cloudflareinsights.com`
- `worker-src`: add `blob:` (required for PDF.js)

Never tighten CSP without testing on production — it breaks fonts, analytics, and WASM.

---

## Performance

- Lighthouse ≥ 95 mobile. CI enforces — build fails on regression.
- Initial JS bundle < 50KB gzipped.
- No PNG/JPEG in UI assets — SVG or WebP/AVIF only.
- Fonts preloaded in `app.html`.

---

## SEO

All metadata generated by `src/lib/utils/seo.ts`. Never hardcoded in pages.
Every tool page: unique title (≤60 chars), unique description (140–155 chars),
canonical URL, WebApplication schema, Open Graph tags.

---

## Accessibility

- All interactive elements keyboard reachable.
- All icons have `aria-label`.
- Color never sole state indicator.
- Focus rings never suppressed.

---

## Adding a New Tool: Checklist

1. Register in `src/lib/registry/tools/[category].tools.ts`
2. Add engine in `src/lib/engines/[category]/`
3. Write unit tests
4. `pnpm build` — page appears at correct URL
5. Lighthouse ≥ 95 mobile
6. URL in `/sitemap.xml`
7. Linked from ≥1 related tool
8. Keyboard navigation works

**Not done until all 8 pass.**

---

## Never Do

- Pre-styled component libraries (no MUI, Chakra, DaisyUI, shadcn)
- Tracking scripts beyond Cloudflare Web Analytics
- Server routes receiving user data
- Top-level imports of processing libraries
- localStorage in components
- Hardcoded hex colors in components
- Modifying `static/_headers` without testing on production