import type { ToolDefinition } from '../types.js';

export const textTools: ToolDefinition[] = [
	{
		id: 'text-word-counter',
		category: 'text',
		slug: 'word-counter',
		displayName: 'tool.text-word-counter.display_name',
		tagline: 'tool.text-word-counter.tagline',
		description: 'tool.text-word-counter.description',
		primaryKeyword: 'tool.text-word-counter.primary_keyword',
		metaTitle: 'tool.text-word-counter.meta_title',
		metaDescription: 'tool.text-word-counter.meta_description',
		engine: 'text',
		operation: 'tool.text-word-counter.operation',
		layoutVariant: 'single-panel',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'This is a sample text to count words. There are two sentences here!'
	},
	{
		id: 'text-readability',
		category: 'text',
		slug: 'readability',
		displayName: 'tool.text-readability.display_name',
		tagline: 'tool.text-readability.tagline',
		description: 'tool.text-readability.description',
		primaryKeyword: 'tool.text-readability.primary_keyword',
		metaTitle: 'tool.text-readability.meta_title',
		metaDescription: 'tool.text-readability.meta_description',
		engine: 'text',
		operation: 'tool.text-readability.operation',
		layoutVariant: 'single-panel',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput:
			'The quick brown fox jumps over the lazy dog. Readability determines how easy your text is to read.'
	},
	{
		id: 'text-line-sorter',
		category: 'text',
		slug: 'line-sorter',
		displayName: 'tool.text-line-sorter.display_name',
		tagline: 'tool.text-line-sorter.tagline',
		description: 'tool.text-line-sorter.description',
		primaryKeyword: 'tool.text-line-sorter.primary_keyword',
		metaTitle: 'tool.text-line-sorter.meta_title',
		metaDescription: 'tool.text-line-sorter.meta_description',
		engine: 'text',
		operation: 'tool.text-line-sorter.operation',
		layoutVariant: 'split',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'Zebra\nApple\nMango\nBanana\nOrange'
	},
	{
		id: 'text-deduplicate',
		category: 'text',
		slug: 'deduplicate',
		displayName: 'tool.text-deduplicate.display_name',
		tagline: 'tool.text-deduplicate.tagline',
		description: 'tool.text-deduplicate.description',
		primaryKeyword: 'tool.text-deduplicate.primary_keyword',
		metaTitle: 'tool.text-deduplicate.meta_title',
		metaDescription: 'tool.text-deduplicate.meta_description',
		engine: 'text',
		operation: 'tool.text-deduplicate.operation',
		layoutVariant: 'split',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'apple\nbanana\napple\norange\nBANANA'
	},
	{
		id: 'text-whitespace',
		category: 'text',
		slug: 'whitespace',
		displayName: 'tool.text-whitespace.display_name',
		tagline: 'tool.text-whitespace.tagline',
		description: 'tool.text-whitespace.description',
		primaryKeyword: 'tool.text-whitespace.primary_keyword',
		metaTitle: 'tool.text-whitespace.meta_title',
		metaDescription: 'tool.text-whitespace.meta_description',
		engine: 'text',
		operation: 'tool.text-whitespace.operation',
		layoutVariant: 'split',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: '   This   has   too  many \t spaces.   \n\n\nAnd  blank  lines.  '
	},
	{
		id: 'text-markdown-to-html',
		category: 'text',
		slug: 'markdown-to-html',
		displayName: 'tool.text-markdown-to-html.display_name',
		tagline: 'tool.text-markdown-to-html.tagline',
		description: 'tool.text-markdown-to-html.description',
		primaryKeyword: 'tool.text-markdown-to-html.primary_keyword',
		metaTitle: 'tool.text-markdown-to-html.meta_title',
		metaDescription: 'tool.text-markdown-to-html.meta_description',
		engine: 'text',
		operation: 'tool.text-markdown-to-html.operation',
		layoutVariant: 'split',
		inputLanguage: 'markdown',
		outputLanguage: 'html',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: '# Hello World\n\nThis is **markdown**.'
	},
	{
		id: 'text-html-to-markdown',
		category: 'text',
		slug: 'html-to-markdown',
		displayName: 'tool.text-html-to-markdown.display_name',
		tagline: 'tool.text-html-to-markdown.tagline',
		description: 'tool.text-html-to-markdown.description',
		primaryKeyword: 'tool.text-html-to-markdown.primary_keyword',
		metaTitle: 'tool.text-html-to-markdown.meta_title',
		metaDescription: 'tool.text-html-to-markdown.meta_description',
		engine: 'text',
		operation: 'tool.text-html-to-markdown.operation',
		layoutVariant: 'split',
		inputLanguage: 'html',
		outputLanguage: 'markdown',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: '<h1>Hello World</h1><p>This is <strong>HTML</strong>.</p>'
	},
	{
		id: 'text-reverser',
		category: 'text',
		slug: 'reverser',
		displayName: 'tool.text-reverser.display_name',
		tagline: 'tool.text-reverser.tagline',
		description: 'tool.text-reverser.description',
		primaryKeyword: 'tool.text-reverser.primary_keyword',
		metaTitle: 'tool.text-reverser.meta_title',
		metaDescription: 'tool.text-reverser.meta_description',
		engine: 'text',
		operation: 'tool.text-reverser.operation',
		layoutVariant: 'bidirectional',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'Reverse this completely'
	}
];
