import type { ToolDefinition } from '../types.js';

export const textTools: ToolDefinition[] = [
	{
		id: 'text-word-counter',
		category: 'text',
		slug: 'word-counter',
		displayName: 'Word Counter',
		tagline: 'Count words, characters, and sentences',
		description: 'Count words, characters, sentences, paragraphs, and reading time instantly.',
		primaryKeyword: 'word counter',
		metaTitle: 'Word Counter & Character Count',
		metaDescription: 'Count words, characters, sentences, paragraphs, and reading time instantly.',
		engine: 'text',
		operation: 'countWords',
		layoutVariant: 'single-panel',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'This is a sample text to count words. There are two sentences here!'
	},
	{
		id: 'text-readability',
		category: 'text',
		slug: 'readability',
		displayName: 'Readability Score',
		tagline: 'Calculate text readability metrics',
		description: 'Calculate Flesch-Kincaid, Gunning Fog, SMOG and other readability indexes.',
		primaryKeyword: 'readability checker',
		metaTitle: 'Readability Score Calculator',
		metaDescription: 'Calculate Flesch-Kincaid, Gunning Fog, SMOG and other readability indexes.',
		engine: 'text',
		operation: 'readability',
		layoutVariant: 'single-panel',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput:
			'The quick brown fox jumps over the lazy dog. Readability determines how easy your text is to read.'
	},
	{
		id: 'text-line-sorter',
		category: 'text',
		slug: 'line-sorter',
		displayName: 'Line Sorter',
		tagline: 'Sort lines alphabetically or numerically',
		description: 'Sort text lines alphabetically, numerically, by length, ascending or descending.',
		primaryKeyword: 'line sorter',
		metaTitle: 'Sort Lines Online',
		metaDescription:
			'Sort text lines alphabetically, numerically, by length, ascending or descending.',
		engine: 'text',
		operation: 'sortLines',
		layoutVariant: 'split',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'Zebra\nApple\nMango\nBanana\nOrange'
	},
	{
		id: 'text-deduplicate',
		category: 'text',
		slug: 'deduplicate',
		displayName: 'Duplicate Line Remover',
		tagline: 'Remove duplicate lines from text',
		description: 'Remove exact duplicate lines from your text, with optional case sensitivity.',
		primaryKeyword: 'remove duplicate lines',
		metaTitle: 'Remove Duplicate Lines',
		metaDescription: 'Remove exact duplicate lines from your text, with optional case sensitivity.',
		engine: 'text',
		operation: 'deduplicateLines',
		layoutVariant: 'split',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'apple\nbanana\napple\norange\nBANANA'
	},
	{
		id: 'text-whitespace',
		category: 'text',
		slug: 'whitespace',
		displayName: 'Whitespace Cleaner',
		tagline: 'Clean up whitespace and formatting',
		description: 'Remove extra spaces, trim lines, normalize newlines, and remove blank lines.',
		primaryKeyword: 'whitespace remover',
		metaTitle: 'Whitespace Cleaner & Formatting tool',
		metaDescription: 'Remove extra spaces, trim lines, normalize newlines, and remove blank lines.',
		engine: 'text',
		operation: 'cleanWhitespace',
		layoutVariant: 'split',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: '   This   has   too  many \t spaces.   \n\n\nAnd  blank  lines.  '
	},
	{
		id: 'text-markdown-to-html',
		category: 'text',
		slug: 'markdown-to-html',
		displayName: 'Markdown to HTML',
		tagline: 'Convert Markdown to raw HTML',
		description: 'Quickly convert Markdown syntax to raw HTML tags.',
		primaryKeyword: 'markdown to html',
		metaTitle: 'Markdown to HTML Converter',
		metaDescription: 'Quickly convert Markdown syntax to raw HTML tags.',
		engine: 'text',
		operation: 'markdownToHtml',
		layoutVariant: 'split',
		inputLanguage: 'markdown',
		outputLanguage: 'html',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: '# Hello World\n\nThis is **markdown**.'
	},
	{
		id: 'text-html-to-markdown',
		category: 'text',
		slug: 'html-to-markdown',
		displayName: 'HTML to Markdown',
		tagline: 'Convert HTML string to Markdown',
		description: 'Convert raw HTML snippets into readable Markdown.',
		primaryKeyword: 'html to markdown',
		metaTitle: 'HTML to Markdown Converter',
		metaDescription: 'Convert raw HTML snippets into readable Markdown.',
		engine: 'text',
		operation: 'htmlToMarkdown',
		layoutVariant: 'split',
		inputLanguage: 'html',
		outputLanguage: 'markdown',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: '<h1>Hello World</h1><p>This is <strong>HTML</strong>.</p>'
	},
	{
		id: 'text-reverser',
		category: 'text',
		slug: 'reverser',
		displayName: 'Text Reverser',
		tagline: 'Reverse chars, words, or lines',
		description: 'Reverse characters, words, or lines of text instantly.',
		primaryKeyword: 'text reverser',
		metaTitle: 'Text Reverser',
		metaDescription: 'Reverse characters, words, or lines of text instantly.',
		engine: 'text',
		operation: 'reverseText',
		layoutVariant: 'bidirectional',
		inputLanguage: 'text',
		outputLanguage: 'text',
		hasTreeView: false,
		relatedTools: [
			{ category: 'json', slug: 'formatter' },
			{ category: 'text', slug: 'word-counter' },
			{ category: 'color', slug: 'contrast' },
			{ category: 'crypto', slug: 'hash' }
		],
		faqs: [],
		useCases: [],
		sampleInput: 'Reverse this completely'
	}
];
