import { parseJSON } from './parser.js';

type JsonScalar = string | number | boolean | null;
type JsonArray = JsonValue[];
interface JsonObject {
	[key: string]: JsonValue;
}
export type JsonValue = JsonScalar | JsonArray | JsonObject;

export interface FormatOptions {
	indent: 2 | 4 | 'tab';
	sortKeys: boolean;
	sortOrder: 'asc' | 'desc';
	trailingCommas: boolean;
	quoteStyle: 'double' | 'single';
	collapseDepth: number | null;
	removeNulls: boolean;
	removeEmptyStrings: boolean;
	removeEmptyArrays: boolean;
	removeEmptyObjects: boolean;
}

export interface JsonStats {
	keys: number;
	values: number;
	strings: number;
	numbers: number;
	booleans: number;
	nulls: number;
	arrays: number;
	objects: number;
	maxDepth: number;
	sizeOriginal: number;
	sizeFormatted: number;
}

export interface FormatResult {
	formatted: string;
	stats: JsonStats;
	warnings: string[];
}

type JsonSchemaType = 'object' | 'array' | 'string' | 'number' | 'integer' | 'boolean' | 'null';

export interface JsonSchema {
	$schema?: string;
	type?: JsonSchemaType | JsonSchemaType[];
	properties?: Record<string, JsonSchema>;
	required?: string[];
	additionalProperties?: boolean;
	items?: JsonSchema;
	anyOf?: JsonSchema[];
	enum?: JsonScalar[];
}

export interface GoStructOptions {
	rootName: string;
	packageName: string;
	includeJsonTags: boolean;
	useOmitempty: boolean;
	usePointersForOptional: boolean;
}

type GoPrimitiveType = 'string' | 'bool' | 'int64' | 'float64';

type GoDescriptor =
	| {
			kind: 'primitive';
			type: GoPrimitiveType;
	  }
	| {
			kind: 'array';
			element: GoDescriptor;
			nullableElements: boolean;
	  }
	| {
			kind: 'object';
			fields: GoFieldDescriptor[];
	  }
	| {
			kind: 'any';
	  };

interface GoFieldDescriptor {
	jsonKey: string;
	descriptor: GoDescriptor;
	optional: boolean;
	nullable: boolean;
}

interface GoGenerationContext {
	options: GoStructOptions;
	usedNames: Set<string>;
	nameBySignature: Map<string, string>;
	structDefinitionByName: Map<string, string>;
	structOrder: string[];
}

export interface TypeScriptTypeOptions {
	rootName: string;
	exportNamedTypes: boolean;
	useSemicolons: boolean;
}

type TypeScriptPrimitive = 'string' | 'number' | 'boolean' | 'null' | 'unknown';

type TypeScriptDescriptor =
	| {
			kind: 'primitive';
			type: TypeScriptPrimitive;
	  }
	| {
			kind: 'array';
			element: TypeScriptDescriptor;
	  }
	| {
			kind: 'object';
			properties: TypeScriptPropertyDescriptor[];
	  }
	| {
			kind: 'union';
			variants: TypeScriptDescriptor[];
	  };

interface TypeScriptPropertyDescriptor {
	jsonKey: string;
	descriptor: TypeScriptDescriptor;
	optional: boolean;
}

interface TypeScriptGenerationContext {
	options: TypeScriptTypeOptions;
	usedNames: Set<string>;
	interfaceNameBySignature: Map<string, string>;
	interfaceDefinitionByName: Map<string, string>;
	interfaceOrder: string[];
}

const DEFAULT_FORMAT_OPTIONS: FormatOptions = {
	indent: 2,
	sortKeys: false,
	sortOrder: 'asc',
	trailingCommas: false,
	quoteStyle: 'double',
	collapseDepth: null,
	removeNulls: false,
	removeEmptyStrings: false,
	removeEmptyArrays: false,
	removeEmptyObjects: false
};

const DEFAULT_GO_STRUCT_OPTIONS: GoStructOptions = {
	rootName: 'AutoGenerated',
	packageName: '',
	includeJsonTags: true,
	useOmitempty: true,
	usePointersForOptional: true
};

const DEFAULT_TYPESCRIPT_TYPE_OPTIONS: TypeScriptTypeOptions = {
	rootName: 'AutoGenerated',
	exportNamedTypes: true,
	useSemicolons: true
};

const TYPESCRIPT_RESERVED_IDENTIFIERS = new Set([
	'any',
	'boolean',
	'break',
	'case',
	'catch',
	'class',
	'const',
	'continue',
	'default',
	'delete',
	'do',
	'else',
	'enum',
	'export',
	'extends',
	'false',
	'finally',
	'for',
	'function',
	'if',
	'import',
	'in',
	'instanceof',
	'interface',
	'let',
	'new',
	'null',
	'number',
	'object',
	'private',
	'protected',
	'public',
	'return',
	'static',
	'string',
	'super',
	'switch',
	'this',
	'throw',
	'true',
	'try',
	'type',
	'typeof',
	'undefined',
	'unknown',
	'var',
	'void',
	'while',
	'with',
	'yield'
]);

const GO_COMMON_INITIALISMS = new Set([
	'api',
	'ascii',
	'cpu',
	'css',
	'dns',
	'guid',
	'html',
	'http',
	'https',
	'id',
	'ip',
	'json',
	'ram',
	'rpc',
	'sla',
	'sql',
	'ssh',
	'tcp',
	'tls',
	'udp',
	'ui',
	'uid',
	'uri',
	'url',
	'utf8',
	'uuid',
	'xml'
]);

export function format(json: string, options: Partial<FormatOptions> = {}): FormatResult {
	const resolved = { ...DEFAULT_FORMAT_OPTIONS, ...options };
	const parsed = parseJSON(json);

	if (!parsed.success) {
		throw new Error(parsed.error.plainLanguageExplanation);
	}

	const warnings: string[] = [];
	const cleaned = cleanJsonValue(parsed.data as JsonValue, resolved);
	const normalized = cleaned === undefined ? null : cleaned;
	const transformed = resolved.sortKeys
		? sortJsonValue(normalized, resolved.sortOrder)
		: normalized;

	if (cleaned === undefined) {
		warnings.push('Cleaning rules removed every value, so the formatter returned null.');
	}

	if (resolved.quoteStyle === 'single') {
		warnings.push('Single quotes produce JSON5-style output, not strict JSON.');
	}

	if (resolved.trailingCommas) {
		warnings.push('Trailing commas produce JSON5-style output, not strict JSON.');
	}

	const formatted = renderJsonValue(transformed, 0, resolved, false);
	const stats = computeStats(transformed, json, formatted);

	return { formatted, stats, warnings };
}

export function minify(json: string): FormatResult {
	return format(json, {
		indent: 2,
		sortKeys: false,
		sortOrder: 'asc',
		trailingCommas: false,
		quoteStyle: 'double',
		collapseDepth: 0,
		removeNulls: false,
		removeEmptyStrings: false,
		removeEmptyArrays: false,
		removeEmptyObjects: false
	});
}

export async function toYaml(json: string): Promise<string> {
	const yaml = await import('js-yaml');
	const parsed = JSON.parse(json) as JsonValue;
	return yaml.dump(parsed, {
		indent: 2,
		lineWidth: 120,
		noRefs: true,
		sortKeys: false
	});
}

export async function toToml(json: string): Promise<string> {
	const { stringify } = await import('smol-toml');
	const parsed = JSON.parse(json) as JsonValue;
	return stringify(parsed);
}

export async function toMarkdownTable(json: string): Promise<string> {
	const parsed = JSON.parse(json) as JsonValue;
	if (!Array.isArray(parsed) || parsed.length === 0) {
		throw new Error('Input must be a non-empty array of objects for Markdown Table conversion');
	}

	const keys = Array.from(
		new Set(
			parsed.flatMap((row) =>
				row && typeof row === 'object' && !Array.isArray(row) ? Object.keys(row) : []
			)
		)
	);

	let markdown = `| ${keys.join(' | ')} |\n`;
	markdown += `| ${keys.map(() => '---').join(' | ')} |\n`;

	for (const row of parsed) {
		if (!row || typeof row !== 'object' || Array.isArray(row)) {
			throw new Error('Each array item must be an object for Markdown Table conversion');
		}

		markdown += `| ${keys
			.map((key) => formatMarkdownCell((row as JsonObject)[key]))
			.join(' | ')} |\n`;
	}

	return markdown;
}

export function toGoStructs(json: string, options: Partial<GoStructOptions> = {}): string {
	const parsed = parseJSON(json);
	if (!parsed.success) {
		throw new Error(parsed.error.plainLanguageExplanation);
	}

	const resolved: GoStructOptions = {
		...DEFAULT_GO_STRUCT_OPTIONS,
		...options,
		rootName: options.rootName?.trim() || DEFAULT_GO_STRUCT_OPTIONS.rootName,
		packageName: options.packageName?.trim() || ''
	};

	const rootDescriptor = inferGoDescriptor([parsed.data]);
	const context: GoGenerationContext = {
		options: resolved,
		usedNames: new Set<string>(),
		nameBySignature: new Map<string, string>(),
		structDefinitionByName: new Map<string, string>(),
		structOrder: []
	};

	const outputSections: string[] = [];

	if (resolved.packageName) {
		outputSections.push(`package ${normalizeGoPackageName(resolved.packageName)}`);
	}

	if (rootDescriptor.kind === 'object') {
		ensureStructFromDescriptor(rootDescriptor, resolved.rootName, context);
		outputSections.push(renderGoStructDefinitions(context));
		return outputSections.filter((section) => section.length > 0).join('\n\n');
	}

	const rootTypeName = reserveGoTypeName(resolved.rootName, context);
	const rootType = resolveGoType(rootDescriptor, context, `${rootTypeName}Item`);
	outputSections.push(`type ${rootTypeName} ${rootType}`);

	if (context.structOrder.length > 0) {
		outputSections.push(renderGoStructDefinitions(context));
	}

	return outputSections.filter((section) => section.length > 0).join('\n\n');
}

export function toTypeScriptTypes(
	json: string,
	options: Partial<TypeScriptTypeOptions> = {}
): string {
	const parsed = parseJSON(json);
	if (!parsed.success) {
		throw new Error(parsed.error.plainLanguageExplanation);
	}

	const resolved: TypeScriptTypeOptions = {
		...DEFAULT_TYPESCRIPT_TYPE_OPTIONS,
		...options,
		rootName: options.rootName?.trim() || DEFAULT_TYPESCRIPT_TYPE_OPTIONS.rootName
	};

	const rootDescriptor = inferTypeScriptDescriptor([parsed.data]);
	const context: TypeScriptGenerationContext = {
		options: resolved,
		usedNames: new Set<string>(),
		interfaceNameBySignature: new Map<string, string>(),
		interfaceDefinitionByName: new Map<string, string>(),
		interfaceOrder: []
	};

	const outputSections: string[] = [];
	let rootTypeName = '';
	let rootType: string | null = null;

	if (rootDescriptor.kind === 'object') {
		rootTypeName = ensureTypeScriptInterface(rootDescriptor, resolved.rootName, context);
	} else {
		rootTypeName = reserveTypeScriptTypeName(resolved.rootName, context);
		rootType = resolveTypeScriptType(rootDescriptor, context, rootTypeName);
	}

	const interfaceDefinitions = renderTypeScriptInterfaces(context);

	if (rootType) {
		const exportKeyword = resolved.exportNamedTypes ? 'export ' : '';
		const suffix = resolved.useSemicolons ? ';' : '';
		outputSections.push(`${exportKeyword}type ${rootTypeName} = ${rootType}${suffix}`);
	}

	if (interfaceDefinitions.length > 0) {
		outputSections.push(interfaceDefinitions);
	}

	return outputSections.join('\n\n');
}

export function generateJsonSchema(json: string): string {
	const parsed = parseJSON(json);
	if (!parsed.success) {
		throw new Error(parsed.error.plainLanguageExplanation);
	}

	const inferred = inferSchemaFromValues([parsed.data as JsonValue]);
	const schema: JsonSchema = {
		$schema: 'https://json-schema.org/draft/2020-12/schema',
		...inferred
	};

	return JSON.stringify(schema, null, 2);
}

export async function jsonpathQuery(json: string, query: string): Promise<unknown> {
	const { JSONPath } = await import('jsonpath-plus');
	const parsed = JSON.parse(json) as JsonValue;
	return JSONPath({ path: query, json: parsed });
}

export async function jmespathQuery(json: string, query: string): Promise<unknown> {
	const mod = await import('jmespath');
	const jmespath = mod.default ?? mod;
	const parsed = JSON.parse(json) as JsonValue;
	return jmespath.search(parsed, query);
}

function formatMarkdownCell(value: unknown): string {
	if (value === null || value === undefined) {
		return '';
	}

	if (typeof value === 'object') {
		return JSON.stringify(value).replaceAll('|', '\\|');
	}

	return String(value).replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function inferSchemaFromValues(values: JsonValue[]): JsonSchema {
	if (values.length === 0) {
		return {};
	}

	if (values.every(isJsonObject)) {
		return inferObjectSchema(values);
	}

	if (values.every(isJsonArray)) {
		return inferArraySchema(values);
	}

	if (values.every(isJsonPrimitive)) {
		return inferPrimitiveSchema(values);
	}

	const variants = dedupeSchemas(values.map((value) => inferSchemaFromValues([value])));
	if (variants.length === 1) {
		return variants[0];
	}

	return { anyOf: variants };
}

function inferObjectSchema(objects: JsonObject[]): JsonSchema {
	const allKeys = new Set<string>();
	const keyCounts = new Map<string, number>();
	const valueBuckets = new Map<string, JsonValue[]>();

	for (const objectValue of objects) {
		for (const [key, value] of Object.entries(objectValue)) {
			allKeys.add(key);
			keyCounts.set(key, (keyCounts.get(key) ?? 0) + 1);
			const existingValues = valueBuckets.get(key) ?? [];
			existingValues.push(value);
			valueBuckets.set(key, existingValues);
		}
	}

	const sortedKeys = Array.from(allKeys).sort((left, right) => left.localeCompare(right));
	const properties: Record<string, JsonSchema> = {};
	for (const key of sortedKeys) {
		properties[key] = inferSchemaFromValues(valueBuckets.get(key) ?? []);
	}

	const required = sortedKeys.filter((key) => (keyCounts.get(key) ?? 0) === objects.length);

	return {
		type: 'object',
		properties,
		required: required.length > 0 ? required : undefined,
		additionalProperties: false
	};
}

function inferArraySchema(arrays: JsonArray[]): JsonSchema {
	const flattened = arrays.flat();
	return {
		type: 'array',
		items: flattened.length > 0 ? inferSchemaFromValues(flattened) : {}
	};
}

function inferPrimitiveSchema(values: JsonScalar[]): JsonSchema {
	const types = normalizePrimitiveTypes(values.map((value) => getPrimitiveSchemaType(value)));
	const enumValues = inferEnum(values);

	return {
		type: types.length === 1 ? types[0] : types,
		enum: enumValues
	};
}

function inferEnum(values: JsonScalar[]): JsonScalar[] | undefined {
	if (values.length < 2) {
		return undefined;
	}

	const uniqueValues = Array.from(new Set(values));
	if (uniqueValues.length === 0 || uniqueValues.length > 8) {
		return undefined;
	}

	if (uniqueValues.length <= 3 || uniqueValues.length < values.length) {
		return uniqueValues;
	}

	return undefined;
}

function normalizePrimitiveTypes(types: JsonSchemaType[]): JsonSchemaType[] {
	const unique = Array.from(new Set(types));
	if (unique.includes('number') && unique.includes('integer')) {
		return unique.filter((type) => type !== 'integer');
	}
	return unique;
}

function getPrimitiveSchemaType(value: JsonScalar): JsonSchemaType {
	if (value === null) return 'null';
	if (typeof value === 'string') return 'string';
	if (typeof value === 'boolean') return 'boolean';
	return Number.isInteger(value) ? 'integer' : 'number';
}

function isJsonPrimitive(value: JsonValue): value is JsonScalar {
	return (
		value === null ||
		typeof value === 'string' ||
		typeof value === 'number' ||
		typeof value === 'boolean'
	);
}

function isJsonArray(value: JsonValue): value is JsonArray {
	return Array.isArray(value);
}

function isJsonObject(value: JsonValue): value is JsonObject {
	return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function dedupeSchemas(schemas: JsonSchema[]): JsonSchema[] {
	const unique = new Map<string, JsonSchema>();
	for (const schema of schemas) {
		const key = JSON.stringify(schema);
		if (!unique.has(key)) {
			unique.set(key, schema);
		}
	}
	return Array.from(unique.values());
}

function cleanJsonValue(value: JsonValue, options: FormatOptions): JsonValue | undefined {
	if (value === null) {
		return options.removeNulls ? undefined : value;
	}

	if (Array.isArray(value)) {
		const nextArray = value
			.map((entry) => cleanJsonValue(entry, options))
			.filter((entry): entry is JsonValue => entry !== undefined);

		if (options.removeEmptyArrays && nextArray.length === 0) {
			return undefined;
		}

		return nextArray;
	}

	if (typeof value === 'object') {
		const nextObjectEntries = Object.entries(value)
			.map(([key, entry]) => [key, cleanJsonValue(entry, options)] as const)
			.filter(([, entry]) => entry !== undefined);

		const nextObject = Object.fromEntries(nextObjectEntries) as JsonObject;

		if (options.removeEmptyObjects && Object.keys(nextObject).length === 0) {
			return undefined;
		}

		return nextObject;
	}

	if (typeof value === 'string' && options.removeEmptyStrings && value.length === 0) {
		return undefined;
	}

	return value;
}

function sortJsonValue(value: JsonValue, direction: 'asc' | 'desc'): JsonValue {
	if (Array.isArray(value)) {
		return value.map((entry) => sortJsonValue(entry, direction));
	}

	if (value && typeof value === 'object') {
		const keys = Object.keys(value).sort((left, right) => {
			const comparison = left.localeCompare(right);
			return direction === 'asc' ? comparison : -comparison;
		});

		return Object.fromEntries(
			keys.map((key) => [key, sortJsonValue((value as JsonObject)[key], direction)])
		) as JsonObject;
	}

	return value;
}

function computeStats(value: JsonValue, original: string, formatted: string): JsonStats {
	const stats: JsonStats = {
		keys: 0,
		values: 0,
		strings: 0,
		numbers: 0,
		booleans: 0,
		nulls: 0,
		arrays: 0,
		objects: 0,
		maxDepth: 0,
		sizeOriginal: new TextEncoder().encode(original).length,
		sizeFormatted: new TextEncoder().encode(formatted).length
	};

	walkStats(value, 0, stats);
	return stats;
}

function walkStats(value: JsonValue, depth: number, stats: JsonStats): void {
	stats.maxDepth = Math.max(stats.maxDepth, depth);

	if (value === null) {
		stats.values++;
		stats.nulls++;
		return;
	}

	if (Array.isArray(value)) {
		stats.values++;
		stats.arrays++;
		for (const entry of value) {
			walkStats(entry, depth + 1, stats);
		}
		return;
	}

	if (typeof value === 'object') {
		stats.values++;
		stats.objects++;
		const entries = Object.entries(value);
		stats.keys += entries.length;
		for (const [, entry] of entries) {
			walkStats(entry, depth + 1, stats);
		}
		return;
	}

	stats.values++;
	switch (typeof value) {
		case 'string':
			stats.strings++;
			break;
		case 'number':
			stats.numbers++;
			break;
		case 'boolean':
			stats.booleans++;
			break;
	}
}

function renderJsonValue(
	value: JsonValue,
	depth: number,
	options: FormatOptions,
	forceInline: boolean
): string {
	if (value === null) {
		return 'null';
	}

	if (typeof value === 'string') {
		return quoteString(value, options.quoteStyle);
	}

	if (typeof value === 'number' || typeof value === 'boolean') {
		return String(value);
	}

	const indentUnit = options.indent === 'tab' ? '\t' : ' '.repeat(options.indent);
	const nextIndent = indentUnit.repeat(depth + 1);
	const currentIndent = indentUnit.repeat(depth);
	const shouldInline =
		forceInline ||
		options.collapseDepth === 0 ||
		(options.collapseDepth !== null && depth >= options.collapseDepth);

	if (Array.isArray(value)) {
		if (value.length === 0) {
			return '[]';
		}

		const items = value.map((entry) => renderJsonValue(entry, depth + 1, options, shouldInline));
		if (shouldInline) {
			return `[${items.join(', ')}${options.trailingCommas ? ',' : ''}]`;
		}

		return `[\n${items
			.map((entry, index) => `${nextIndent}${entry}${commaSuffix(index, items.length, options)}`)
			.join('\n')}\n${currentIndent}]`;
	}

	const entries = Object.entries(value);
	if (entries.length === 0) {
		return '{}';
	}

	const renderedEntries = entries.map(([key, entry]) => {
		const renderedKey = quoteString(key, options.quoteStyle);
		const renderedValue = renderJsonValue(entry, depth + 1, options, shouldInline);
		return `${renderedKey}: ${renderedValue}`;
	});

	if (shouldInline) {
		return `{ ${renderedEntries.join(', ')}${options.trailingCommas ? ',' : ''} }`;
	}

	return `{\n${renderedEntries
		.map(
			(entry, index) =>
				`${nextIndent}${entry}${commaSuffix(index, renderedEntries.length, options)}`
		)
		.join('\n')}\n${currentIndent}}`;
}

function commaSuffix(index: number, total: number, options: FormatOptions): string {
	if (index < total - 1) {
		return ',';
	}

	return options.trailingCommas ? ',' : '';
}

function quoteString(value: string, style: 'double' | 'single'): string {
	const escaped = value
		.replaceAll('\\', '\\\\')
		.replaceAll('\n', '\\n')
		.replaceAll('\r', '\\r')
		.replaceAll('\t', '\\t');

	if (style === 'single') {
		return `'${escaped.replaceAll("'", "\\'")}'`;
	}

	return `"${escaped.replaceAll('"', '\\"')}"`;
}

function inferGoDescriptor(samples: unknown[]): GoDescriptor {
	const definedSamples = samples.filter((sample) => sample !== undefined);
	if (definedSamples.length === 0) {
		return { kind: 'any' };
	}

	const nonNullSamples = definedSamples.filter((sample) => sample !== null);
	if (nonNullSamples.length === 0) {
		return { kind: 'any' };
	}

	if (nonNullSamples.every(isGoObjectSample)) {
		return inferGoObjectDescriptor(nonNullSamples as Record<string, unknown>[]);
	}

	if (nonNullSamples.every(Array.isArray)) {
		return inferGoArrayDescriptor(nonNullSamples as unknown[][]);
	}

	if (nonNullSamples.every((sample) => typeof sample === 'string')) {
		return { kind: 'primitive', type: 'string' };
	}

	if (nonNullSamples.every((sample) => typeof sample === 'boolean')) {
		return { kind: 'primitive', type: 'bool' };
	}

	if (nonNullSamples.every((sample) => typeof sample === 'number')) {
		return {
			kind: 'primitive',
			type: nonNullSamples.every((sample) => Number.isInteger(sample)) ? 'int64' : 'float64'
		};
	}

	return { kind: 'any' };
}

function inferGoObjectDescriptor(samples: Record<string, unknown>[]): GoDescriptor {
	const allKeys = new Set<string>();
	for (const sample of samples) {
		for (const key of Object.keys(sample)) {
			allKeys.add(key);
		}
	}

	const sortedKeys = Array.from(allKeys).sort((left, right) => left.localeCompare(right));
	const fields: GoFieldDescriptor[] = sortedKeys.map((jsonKey) => {
		let presentCount = 0;
		let nullable = false;
		const values: unknown[] = [];

		for (const sample of samples) {
			if (Object.prototype.hasOwnProperty.call(sample, jsonKey)) {
				presentCount += 1;
				const value = sample[jsonKey];
				if (value === null) {
					nullable = true;
				}
				values.push(value);
			}
		}

		const descriptor = inferGoDescriptor(values);
		return {
			jsonKey,
			descriptor,
			nullable,
			optional: presentCount < samples.length
		};
	});

	return {
		kind: 'object',
		fields
	};
}

function inferGoArrayDescriptor(samples: unknown[][]): GoDescriptor {
	const flattened = samples.flat();
	const nonNullElements = flattened.filter((item) => item !== null);
	return {
		kind: 'array',
		nullableElements: flattened.length > nonNullElements.length,
		element: inferGoDescriptor(nonNullElements)
	};
}

function resolveGoType(
	descriptor: GoDescriptor,
	context: GoGenerationContext,
	nameHint: string
): string {
	switch (descriptor.kind) {
		case 'primitive':
			return descriptor.type;
		case 'any':
			return 'any';
		case 'array': {
			const elementNameHint = nameHint.endsWith('Item') ? nameHint : `${nameHint}Item`;
			const elementType = resolveGoType(descriptor.element, context, elementNameHint);
			const listElementType =
				descriptor.nullableElements && canBePointerWrapped(elementType)
					? `*${elementType}`
					: elementType;
			return `[]${listElementType}`;
		}
		case 'object':
			return ensureStructFromDescriptor(descriptor, nameHint, context);
	}
}

function ensureStructFromDescriptor(
	descriptor: Extract<GoDescriptor, { kind: 'object' }>,
	nameHint: string,
	context: GoGenerationContext
): string {
	const signature = getDescriptorSignature(descriptor);
	const existing = context.nameBySignature.get(signature);
	if (existing) {
		return existing;
	}

	const typeName = reserveGoTypeName(nameHint, context);
	context.nameBySignature.set(signature, typeName);
	context.structOrder.push(typeName);

	const usedFieldNames = new Set<string>();
	const fieldLines = descriptor.fields.map((field) => {
		const baseName = toGoIdentifier(field.jsonKey, 'Field');
		const fieldName = reserveUniqueFieldName(baseName, usedFieldNames);
		let fieldType = resolveGoType(field.descriptor, context, `${typeName}${fieldName}`);
		const shouldUsePointer =
			context.options.usePointersForOptional &&
			(field.optional || field.nullable) &&
			canBePointerWrapped(fieldType);

		if (shouldUsePointer) {
			fieldType = `*${fieldType}`;
		}

		const structTag = buildGoStructTag(
			field.jsonKey,
			context.options.includeJsonTags,
			context.options.useOmitempty && (field.optional || field.nullable)
		);

		return `\t${fieldName} ${fieldType}${structTag}`;
	});

	const structDefinition =
		fieldLines.length > 0
			? `type ${typeName} struct {\n${fieldLines.join('\n')}\n}`
			: `type ${typeName} struct {}`;
	context.structDefinitionByName.set(typeName, structDefinition);

	return typeName;
}

function renderGoStructDefinitions(context: GoGenerationContext): string {
	return context.structOrder
		.map((typeName) => context.structDefinitionByName.get(typeName))
		.filter((definition): definition is string => Boolean(definition))
		.join('\n\n');
}

function getDescriptorSignature(descriptor: GoDescriptor): string {
	switch (descriptor.kind) {
		case 'primitive':
			return `primitive:${descriptor.type}`;
		case 'any':
			return 'any';
		case 'array':
			return `array:${descriptor.nullableElements ? 'nullable' : 'strict'}:${getDescriptorSignature(descriptor.element)}`;
		case 'object':
			return `object:${descriptor.fields
				.map((field) => {
					const optional = field.optional ? 'optional' : 'required';
					const nullable = field.nullable ? 'nullable' : 'strict';
					return `${field.jsonKey}:${optional}:${nullable}:${getDescriptorSignature(field.descriptor)}`;
				})
				.join('|')}`;
	}
}

function reserveGoTypeName(nameHint: string, context: GoGenerationContext): string {
	const normalized = toGoIdentifier(nameHint, 'AutoGenerated');
	let candidate = normalized;
	let suffix = 2;

	while (context.usedNames.has(candidate)) {
		candidate = `${normalized}${suffix}`;
		suffix += 1;
	}

	context.usedNames.add(candidate);
	return candidate;
}

function reserveUniqueFieldName(name: string, usedNames: Set<string>): string {
	let candidate = name;
	let suffix = 2;

	while (usedNames.has(candidate)) {
		candidate = `${name}${suffix}`;
		suffix += 1;
	}

	usedNames.add(candidate);
	return candidate;
}

function toGoIdentifier(value: string, fallback: string): string {
	const normalized = value.replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2');
	const tokens = normalized.match(/[A-Za-z0-9]+/g) ?? [];
	const identifier = tokens
		.map((token) => {
			if (/^\d+$/.test(token)) {
				return token;
			}

			const lower = token.toLowerCase();
			if (GO_COMMON_INITIALISMS.has(lower)) {
				return lower.toUpperCase();
			}

			return `${lower.charAt(0).toUpperCase()}${lower.slice(1)}`;
		})
		.join('');

	const fallbackIdentifier = `${fallback.charAt(0).toUpperCase()}${fallback.slice(1)}`;
	const safeIdentifier = identifier.length > 0 ? identifier : fallbackIdentifier;

	if (/^\d/.test(safeIdentifier)) {
		return `${fallbackIdentifier}${safeIdentifier}`;
	}

	return `${safeIdentifier.charAt(0).toUpperCase()}${safeIdentifier.slice(1)}`;
}

function normalizeGoPackageName(packageName: string): string {
	const normalized = packageName
		.toLowerCase()
		.replaceAll(/[^a-z0-9_]/g, '_')
		.replace(/^_+/g, '');

	if (normalized.length === 0 || /^\d/.test(normalized)) {
		return 'main';
	}

	return normalized;
}

function buildGoStructTag(key: string, includeTags: boolean, addOmitempty: boolean): string {
	if (!includeTags) {
		return '';
	}

	const suffix = addOmitempty ? ',omitempty' : '';
	const escapedKey = key.replaceAll('"', '\\"');
	return ` \`json:"${escapedKey}${suffix}"\``;
}

function canBePointerWrapped(goType: string): boolean {
	if (goType === 'any' || goType.startsWith('*')) {
		return false;
	}

	if (goType.startsWith('[]') || goType.startsWith('map[')) {
		return false;
	}

	return true;
}

function inferTypeScriptDescriptor(samples: unknown[]): TypeScriptDescriptor {
	const definedSamples = samples.filter((sample) => sample !== undefined);
	if (definedSamples.length === 0) {
		return { kind: 'primitive', type: 'unknown' };
	}

	const nonNullSamples = definedSamples.filter((sample) => sample !== null);
	const includesNull = nonNullSamples.length < definedSamples.length;

	if (nonNullSamples.length === 0) {
		return { kind: 'primitive', type: 'null' };
	}

	let descriptor: TypeScriptDescriptor;

	if (nonNullSamples.every(isTypeScriptObjectSample)) {
		descriptor = inferTypeScriptObjectDescriptor(nonNullSamples as Record<string, unknown>[]);
	} else if (nonNullSamples.every(Array.isArray)) {
		descriptor = inferTypeScriptArrayDescriptor(nonNullSamples as unknown[][]);
	} else if (nonNullSamples.every((sample) => typeof sample === 'string')) {
		descriptor = { kind: 'primitive', type: 'string' };
	} else if (nonNullSamples.every((sample) => typeof sample === 'number')) {
		descriptor = { kind: 'primitive', type: 'number' };
	} else if (nonNullSamples.every((sample) => typeof sample === 'boolean')) {
		descriptor = { kind: 'primitive', type: 'boolean' };
	} else {
		descriptor = createTypeScriptUnionDescriptor(
			nonNullSamples.map((sample) => inferTypeScriptDescriptor([sample]))
		);
	}

	if (!includesNull) {
		return descriptor;
	}

	return createTypeScriptUnionDescriptor([descriptor, { kind: 'primitive', type: 'null' }]);
}

function inferTypeScriptObjectDescriptor(samples: Record<string, unknown>[]): TypeScriptDescriptor {
	const allKeys = new Set<string>();
	for (const sample of samples) {
		for (const key of Object.keys(sample)) {
			allKeys.add(key);
		}
	}

	const sortedKeys = Array.from(allKeys).sort((left, right) => left.localeCompare(right));
	const properties: TypeScriptPropertyDescriptor[] = sortedKeys.map((jsonKey) => {
		let presentCount = 0;
		const values: unknown[] = [];

		for (const sample of samples) {
			if (!Object.prototype.hasOwnProperty.call(sample, jsonKey)) {
				continue;
			}

			presentCount += 1;
			values.push(sample[jsonKey]);
		}

		return {
			jsonKey,
			descriptor: inferTypeScriptDescriptor(values),
			optional: presentCount < samples.length
		};
	});

	return {
		kind: 'object',
		properties
	};
}

function inferTypeScriptArrayDescriptor(samples: unknown[][]): TypeScriptDescriptor {
	const flattened = samples.flat();
	if (flattened.length === 0) {
		return {
			kind: 'array',
			element: { kind: 'primitive', type: 'unknown' }
		};
	}

	return {
		kind: 'array',
		element: inferTypeScriptDescriptor(flattened)
	};
}

function createTypeScriptUnionDescriptor(variants: TypeScriptDescriptor[]): TypeScriptDescriptor {
	const flattened = flattenTypeScriptUnionVariants(variants);
	const uniqueBySignature = new Map<string, TypeScriptDescriptor>();

	for (const variant of flattened) {
		const signature = getTypeScriptDescriptorSignature(variant);
		if (!uniqueBySignature.has(signature)) {
			uniqueBySignature.set(signature, variant);
		}
	}

	const normalized = Array.from(uniqueBySignature.values()).sort(compareTypeScriptDescriptors);
	if (normalized.length === 1) {
		return normalized[0];
	}

	return {
		kind: 'union',
		variants: normalized
	};
}

function flattenTypeScriptUnionVariants(variants: TypeScriptDescriptor[]): TypeScriptDescriptor[] {
	const flattened: TypeScriptDescriptor[] = [];

	for (const variant of variants) {
		if (variant.kind === 'union') {
			flattened.push(...flattenTypeScriptUnionVariants(variant.variants));
			continue;
		}

		flattened.push(variant);
	}

	return flattened;
}

function compareTypeScriptDescriptors(
	left: TypeScriptDescriptor,
	right: TypeScriptDescriptor
): number {
	const rankDiff = getTypeScriptDescriptorRank(left) - getTypeScriptDescriptorRank(right);
	if (rankDiff !== 0) {
		return rankDiff;
	}

	return getTypeScriptDescriptorSignature(left).localeCompare(
		getTypeScriptDescriptorSignature(right)
	);
}

function getTypeScriptDescriptorRank(descriptor: TypeScriptDescriptor): number {
	if (descriptor.kind === 'primitive') {
		switch (descriptor.type) {
			case 'string':
				return 0;
			case 'number':
				return 1;
			case 'boolean':
				return 2;
			case 'unknown':
				return 6;
			case 'null':
				return 7;
		}
	}

	if (descriptor.kind === 'object') {
		return 3;
	}

	if (descriptor.kind === 'array') {
		return 4;
	}

	return 5;
}

function resolveTypeScriptType(
	descriptor: TypeScriptDescriptor,
	context: TypeScriptGenerationContext,
	nameHint: string
): string {
	switch (descriptor.kind) {
		case 'primitive':
			return descriptor.type;
		case 'array': {
			const elementType = resolveTypeScriptType(descriptor.element, context, `${nameHint}Item`);
			const normalized = needsParenthesizedArrayElementType(elementType)
				? `(${elementType})`
				: elementType;
			return `${normalized}[]`;
		}
		case 'object':
			return ensureTypeScriptInterface(descriptor, nameHint, context);
		case 'union':
			return descriptor.variants
				.map((variant, index) =>
					resolveTypeScriptType(variant, context, `${nameHint}Variant${index + 1}`)
				)
				.join(' | ');
	}
}

function ensureTypeScriptInterface(
	descriptor: Extract<TypeScriptDescriptor, { kind: 'object' }>,
	nameHint: string,
	context: TypeScriptGenerationContext
): string {
	const signature = getTypeScriptDescriptorSignature(descriptor);
	const existing = context.interfaceNameBySignature.get(signature);
	if (existing) {
		return existing;
	}

	const typeName = reserveTypeScriptTypeName(nameHint, context);
	context.interfaceNameBySignature.set(signature, typeName);
	context.interfaceOrder.push(typeName);

	const exportKeyword = context.options.exportNamedTypes ? 'export ' : '';
	const suffix = context.options.useSemicolons ? ';' : '';
	const propertyLines = descriptor.properties.map((property) => {
		const propertyName = toTypeScriptPropertyName(property.jsonKey);
		const propertyType = resolveTypeScriptType(
			property.descriptor,
			context,
			`${typeName}${toTypeScriptTypeName(property.jsonKey, 'Field')}`
		);
		const optionalMarker = property.optional ? '?' : '';
		return `\t${propertyName}${optionalMarker}: ${propertyType}${suffix}`;
	});

	const definition =
		propertyLines.length > 0
			? `${exportKeyword}interface ${typeName} {\n${propertyLines.join('\n')}\n}`
			: `${exportKeyword}interface ${typeName} {}`;

	context.interfaceDefinitionByName.set(typeName, definition);
	return typeName;
}

function renderTypeScriptInterfaces(context: TypeScriptGenerationContext): string {
	return context.interfaceOrder
		.map((typeName) => context.interfaceDefinitionByName.get(typeName))
		.filter((definition): definition is string => Boolean(definition))
		.join('\n\n');
}

function reserveTypeScriptTypeName(nameHint: string, context: TypeScriptGenerationContext): string {
	const normalized = toTypeScriptTypeName(nameHint, 'AutoGenerated');
	let candidate = normalized;
	let suffix = 2;

	while (context.usedNames.has(candidate)) {
		candidate = `${normalized}${suffix}`;
		suffix += 1;
	}

	context.usedNames.add(candidate);
	return candidate;
}

function toTypeScriptTypeName(value: string, fallback: string): string {
	const normalized = value.replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2');
	const tokens = normalized.match(/[A-Za-z0-9]+/g) ?? [];
	const identifier = tokens
		.map((token) => {
			if (/^\d+$/.test(token)) {
				return token;
			}

			const lower = token.toLowerCase();
			return `${lower.charAt(0).toUpperCase()}${lower.slice(1)}`;
		})
		.join('');

	const fallbackIdentifier = `${fallback.charAt(0).toUpperCase()}${fallback.slice(1)}`;
	let safeIdentifier = identifier.length > 0 ? identifier : fallbackIdentifier;

	if (/^\d/.test(safeIdentifier)) {
		safeIdentifier = `${fallbackIdentifier}${safeIdentifier}`;
	}

	if (TYPESCRIPT_RESERVED_IDENTIFIERS.has(safeIdentifier.toLowerCase())) {
		safeIdentifier = `${safeIdentifier}Type`;
	}

	return `${safeIdentifier.charAt(0).toUpperCase()}${safeIdentifier.slice(1)}`;
}

function toTypeScriptPropertyName(jsonKey: string): string {
	if (/^[$A-Za-z_][$A-Za-z0-9_]*$/.test(jsonKey)) {
		return jsonKey;
	}

	const escaped = jsonKey.replaceAll('\\', '\\\\').replaceAll('"', '\\"');
	return `"${escaped}"`;
}

function needsParenthesizedArrayElementType(elementType: string): boolean {
	return elementType.includes(' | ') || elementType.includes('&');
}

function getTypeScriptDescriptorSignature(descriptor: TypeScriptDescriptor): string {
	switch (descriptor.kind) {
		case 'primitive':
			return `primitive:${descriptor.type}`;
		case 'array':
			return `array:${getTypeScriptDescriptorSignature(descriptor.element)}`;
		case 'object':
			return `object:${descriptor.properties
				.map(
					(property) =>
						`${property.jsonKey}:${property.optional ? 'optional' : 'required'}:${getTypeScriptDescriptorSignature(property.descriptor)}`
				)
				.join('|')}`;
		case 'union': {
			const variantSignatures = descriptor.variants
				.map((variant) => getTypeScriptDescriptorSignature(variant))
				.sort((left, right) => left.localeCompare(right));
			return `union:${variantSignatures.join('|')}`;
		}
	}
}

function isTypeScriptObjectSample(sample: unknown): sample is Record<string, unknown> {
	return sample !== null && typeof sample === 'object' && !Array.isArray(sample);
}

function isGoObjectSample(sample: unknown): sample is Record<string, unknown> {
	return sample !== null && typeof sample === 'object' && !Array.isArray(sample);
}
