export {
	IMAGE_CONVERTER_DEFAULT_OPTIONS,
	IMAGE_CONVERTER_WORKER_THRESHOLD_BYTES,
	IMAGE_RESIZER_DEFAULT_OPTIONS,
	IMAGE_RESIZER_WORKER_THRESHOLD_BYTES,
	SVG_OPTIMIZER_DEFAULT_OPTIONS,
	SVG_OPTIMIZER_WORKER_THRESHOLD_BYTES,
	computeScaledDimensions,
	convertImageFormat,
	getImageConversionExtension,
	getSvgUtf8ByteSize,
	looksLikeSvgDocument,
	normalizeImageConversionOptions,
	normalizeImageResizeOptions,
	normalizeSvgOptimizeOptions,
	optimizeSvg,
	readImageFileAsDataUrl,
	readSvgFileAsText,
	resizeImage,
	shouldUseImageConverterWorker,
	shouldUseImageResizerWorker,
	shouldUseSvgOptimizerWorker,
	summarizeSvg,
	type ImageConversionInput,
	type ImageConversionMetadata,
	type ImageConversionOptions,
	type ImageConversionOutputFormat,
	type ImageConversionResult,
	type ImageConverterWorkerRequest,
	type ImageConverterWorkerResponse,
	type ImageResizeMode,
	type ImageResizeOutputFormat,
	type ImageResizeInput,
	type ImageResizeOptions,
	type ImageResizeMetadata,
	type ImageResizeResult,
	type ImageResizerWorkerRequest,
	type ImageResizerWorkerResponse
} from './image.engine.js';
export {
	buildSvgOptimizerConfig,
	type SvgDocumentSummary,
	type SvgOptimizeInput,
	type SvgOptimizeMetadata,
	type SvgOptimizeOptions,
	type SvgOptimizeResult,
	type SvgOptimizerConfig,
	type SvgOptimizerWorkerRequest,
	type SvgOptimizerWorkerResponse
} from './svg-optimizer.engine.js';
