export {
	IMAGE_CONVERTER_DEFAULT_OPTIONS,
	IMAGE_CONVERTER_WORKER_THRESHOLD_BYTES,
	IMAGE_RESIZER_DEFAULT_OPTIONS,
	IMAGE_RESIZER_WORKER_THRESHOLD_BYTES,
	computeScaledDimensions,
	convertImageFormat,
	getImageConversionExtension,
	normalizeImageConversionOptions,
	normalizeImageResizeOptions,
	readImageFileAsDataUrl,
	resizeImage,
	shouldUseImageConverterWorker,
	shouldUseImageResizerWorker,
	type ImageConversionInput,
	type ImageConversionMetadata,
	type ImageConversionOptions,
	type ImageConversionOutputFormat,
	type ImageConversionResult,
	type ImageConverterWorkerRequest,
	type ImageConverterWorkerResponse,
	type ImageResizeMode,
	type ImageResizeOutputFormat,
	type ImageResizeInput,
	type ImageResizeOptions,
	type ImageResizeMetadata,
	type ImageResizeResult,
	type ImageResizerWorkerRequest,
	type ImageResizerWorkerResponse
} from './image.engine.js';

export {
	IMAGE_BASE64_WORKER_THRESHOLD_BYTES,
	IMAGE_BASE64_WORKER_THRESHOLD_BYTES as IMAGE_BASE64_TEXT_WORKER_THRESHOLD_BYTES,
	decodeBase64ToImage,
	encodeImageToBase64,
	readImageFileAsArrayBuffer,
	shouldUseBase64ToImageWorker,
	shouldUseImageToBase64Worker,
	type Base64ToImageMetrics,
	type Base64ToImageOptions,
	type Base64ToImageResult,
	type Base64ToImageWorkerRequest,
	type Base64ToImageWorkerResponse,
	type ImageToBase64Input,
	type ImageToBase64Metrics,
	type ImageToBase64Result,
	type ImageToBase64WorkerRequest,
	type ImageToBase64WorkerResponse
} from './image-base64.engine.js';

export {
	buildSvgOptimizerConfig,
	SVG_OPTIMIZER_DEFAULT_OPTIONS,
	SVG_OPTIMIZER_WORKER_THRESHOLD_BYTES,
	getSvgUtf8ByteSize,
	looksLikeSvgDocument,
	normalizeSvgOptimizeOptions,
	optimizeSvg,
	readSvgFileAsText,
	shouldUseSvgOptimizerWorker,
	summarizeSvg,
	type SvgDocumentSummary,
	type SvgOptimizeInput,
	type SvgOptimizeMetadata,
	type SvgOptimizeOptions,
	type SvgOptimizeResult,
	type SvgOptimizerConfig,
	type SvgOptimizerWorkerRequest,
	type SvgOptimizerWorkerResponse
} from './svg-optimizer.engine.js';
