import {
	GITIGNORE_TEMPLATES,
	GITIGNORE_TEMPLATE_KEYS,
	type GitignoreTemplateKey
} from './gitignore-templates.js';

export function listGitignoreTemplateKeys(): readonly GitignoreTemplateKey[] {
	return GITIGNORE_TEMPLATE_KEYS;
}

export function mergeGitignoreTemplates(selected: ReadonlyArray<GitignoreTemplateKey>): string {
	const unique = [...new Set(selected)].sort((a, b) => a.localeCompare(b));
	const header =
		'# Generated by fmtly — merged curated .gitignore fragments (common stacks + OS/IDE noise).\n';
	const parts: string[] = [header];
	for (const key of unique) {
		const body = GITIGNORE_TEMPLATES[key];
		if (!body) continue;
		parts.push('');
		parts.push(`# --- ${key} ---`);
		parts.push(body.trimEnd());
	}
	return `${parts.join('\n')}\n`;
}
