export {
	analyzeText,
	convertTextCases,
	convertMarkdownToHtml,
	generateLoremIpsum,
	reverseText,
	removeDuplicateLines,
	cleanWhitespace,
	analyzeRegexTester,
	stringifyRegexTesterFlags,
	getRegexTesterFlagSupport,
	REGEX_TESTER_FLAG_ORDER,
	processTextEscape,
	shouldUseTextEscapeWorker,
	TEXT_ESCAPE_WORKER_THRESHOLD_BYTES,
	type TextCounterMetrics,
	type TextCaseConversions,
	type MarkdownToHtmlOptions,
	type MarkdownToHtmlResult,
	type MarkdownToHtmlStats,
	type MarkdownToHtmlWarningCode,
	type LoremGenerationMode,
	type LoremOutputFormat,
	type LoremGenerationOptions,
	type LoremGenerationResult,
	type TextReverseResults,
	type TextDuplicateRemovalResult,
	type TextWhitespaceCleanupResult,
	type TextWhitespaceCleanupOptions,
	type RegexTesterFlag,
	type RegexTesterFlags,
	type RegexTesterErrorCode,
	type RegexTesterError,
	type RegexTesterCaptureGroup,
	type RegexTesterNamedCaptureGroup,
	type RegexTesterMatch,
	type RegexTesterTextSegment,
	type RegexTesterAnalyzeOptions,
	type RegexTesterResult,
	type TextEscapeFormat,
	type TextEscapeAction,
	type TextEscapeWarningCode,
	type TextEscapeErrorCode,
	type TextEscapeError,
	type TextEscapeOptions,
	type TextEscapeResult,
	type TextEscapeWorkerRequest,
	type TextEscapeWorkerResponse
} from './text.engine.js';

export {
	diffTexts,
	generateUnifiedDiff,
	generateSideBySideDiff,
	type TextDiffOptions,
	type TextDiffLine,
	type TextDiffHunk,
	type TextDiffResult,
	type TextDiffStats
} from './diff.js';
