export {
	analyzeText,
	convertTextCases,
	convertMarkdownToHtml,
	generateLoremIpsum,
	reverseText,
	removeDuplicateLines,
	sortTextLines,
	cleanWhitespace,
	analyzeRegexTester,
	stringifyRegexTesterFlags,
	getRegexTesterFlagSupport,
	REGEX_TESTER_FLAG_ORDER,
	DEFAULT_TEXT_LINE_SORT_OPTIONS,
	processTextEscape,
	shouldUseTextEscapeWorker,
	TEXT_ESCAPE_WORKER_THRESHOLD_BYTES,
	analyzeTextReadability,
	shouldUseTextReadabilityWorker,
	TEXT_READABILITY_WORKER_THRESHOLD_BYTES,
	processTextMorse,
	shouldUseTextMorseWorker,
	TEXT_MORSE_WORKER_THRESHOLD_BYTES,
	type TextCounterMetrics,
	type TextCaseConversions,
	type MarkdownToHtmlOptions,
	type MarkdownToHtmlResult,
	type MarkdownToHtmlStats,
	type MarkdownToHtmlWarningCode,
	type LoremGenerationMode,
	type LoremOutputFormat,
	type LoremGenerationOptions,
	type LoremGenerationResult,
	type TextReverseResults,
	type TextDuplicateRemovalResult,
	type TextLineSortMode,
	type TextLineSortDirection,
	type TextLineSortOptions,
	type TextLineSortResult,
	type TextWhitespaceCleanupResult,
	type TextWhitespaceCleanupOptions,
	type RegexTesterFlag,
	type RegexTesterFlags,
	type RegexTesterErrorCode,
	type RegexTesterError,
	type RegexTesterCaptureGroup,
	type RegexTesterNamedCaptureGroup,
	type RegexTesterMatch,
	type RegexTesterTextSegment,
	type RegexTesterAnalyzeOptions,
	type RegexTesterResult,
	type TextEscapeFormat,
	type TextEscapeAction,
	type TextEscapeWarningCode,
	type TextEscapeErrorCode,
	type TextEscapeError,
	type TextEscapeOptions,
	type TextEscapeResult,
	type TextEscapeWorkerRequest,
	type TextEscapeWorkerResponse,
	type TextReadabilityWarningCode,
	type TextReadabilityLevel,
	type TextReadabilityResult,
	type TextReadabilityWorkerRequest,
	type TextReadabilityWorkerResponse,
	type TextMorseMode,
	type TextMorseWordSeparator,
	type TextMorseWarningCode,
	type TextMorseOptions,
	type TextMorseResult,
	type TextMorseWorkerRequest,
	type TextMorseWorkerResponse
} from './text.engine.js';

export {
	diffTexts,
	generateUnifiedDiff,
	generateSideBySideDiff,
	type TextDiffOptions,
	type TextDiffLine,
	type TextDiffHunk,
	type TextDiffResult,
	type TextDiffStats
} from './diff.js';
