export {
	analyzeText,
	convertTextCases,
	convertMarkdownToHtml,
	generateLoremIpsum,
	reverseText,
	removeDuplicateLines,
	sortTextLines,
	cleanWhitespace,
	analyzeRegexTester,
	stringifyRegexTesterFlags,
	getRegexTesterFlagSupport,
	REGEX_TESTER_FLAG_ORDER,
	DEFAULT_TEXT_LINE_SORT_OPTIONS,
	type TextCounterMetrics,
	type TextCaseConversions,
	type MarkdownToHtmlOptions,
	type MarkdownToHtmlResult,
	type MarkdownToHtmlStats,
	type MarkdownToHtmlWarningCode,
	type LoremGenerationMode,
	type LoremOutputFormat,
	type LoremGenerationOptions,
	type LoremGenerationResult,
	type TextReverseResults,
	type TextDuplicateRemovalResult,
	type TextLineSortMode,
	type TextLineSortDirection,
	type TextLineSortOptions,
	type TextLineSortResult,
	type TextWhitespaceCleanupResult,
	type TextWhitespaceCleanupOptions,
	type RegexTesterFlag,
	type RegexTesterFlags,
	type RegexTesterErrorCode,
	type RegexTesterError,
	type RegexTesterCaptureGroup,
	type RegexTesterNamedCaptureGroup,
	type RegexTesterMatch,
	type RegexTesterTextSegment,
	type RegexTesterAnalyzeOptions,
	type RegexTesterResult
} from './text.engine.js';

export {
	diffTexts,
	generateUnifiedDiff,
	generateSideBySideDiff,
	type TextDiffOptions,
	type TextDiffLine,
	type TextDiffHunk,
	type TextDiffResult,
	type TextDiffStats
} from './diff.js';
